name: Test
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test_sqlite:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          ### TEST ALL RUBY VERSIONS
          - ruby: 2.3 ### min version supported by Bundler 2.x, ruby: 2.3
          - ruby: 2.4
          - ruby: 2.5
          - ruby: 2.6
          - ruby: 2.7
          - ruby: "3.0" ### must be quoted otherwise will be treated as "3" which resolves to latest 3.x version
          - ruby: 3.1

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"

    steps:
    - uses: actions/checkout@v2

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"

    - name: Bundle
      run: |
        gem install bundler
        bundle install

    - name: Run tests
      run: |
        bundle exec rake
